### ISSUE TITLE
Make for sve 

### ISSUE THREAD

**Issue by lh12565** [TheJacksonLaboratory/SVE#11]
I have downloaded all SV softeware, such as Delly, Lumpy before I install the SVE. So I guess I don't need to download theses SV pacakages to "sve/SVE-master/src". Howerver, when I do this command "make sve ", there is a error:

- Building in speedseq
sed -i 's#CXX    = g++ $(ROOTFLAGS)#CXX    = g++ -std=c++11 $(ROOTFLAGS)#g' src/speedseq/src/cnvnator/Makefile
sed: can't read src/speedseq/src/cnvnator/Makefile: No such file or directory
make: *** [Makefile:61: speedseq] Error 2

How can I solve this problem?
Thanks!

Luo Hao
2018.10.17

**Comment by lslochov** [comment]
Hi Luo, my suspicion here is that you may be using a non-standard directory structure that SVE isn't expecting. The top-level Makefile is expecting its dependent files to be exactly where they are in the distributed source code. I take it the "sve" folder in "sve/SVE-master/src" is the top level of the SVE distribution that you checked out, and the source code of the component tools is in "src"? The Makefile will be expecting speedseq and other tools to be under "${SVE_HOME}/src" so if they're actually under "${SVE_HOME}/SVE-master/src" the make command will not work. If I've misunderstood your directory setup, or any other issues come up, let me know and I'll investigate further.
