### ISSUE TITLE
Help running Docker

### ISSUE THREAD

**Issue by MaestSi** [TheJacksonLaboratory/SVE#12]
Dear SVE developers,
I would like to run SVE through Docker.
I pulled the image with docker pull wanpinglee/sve:0.1.0 and verified it worked.
What is the command I should use?
I tried with:
`docker run -v <Local input dir>:/tools/SVE/in -v <Local output dir>:/tools/SVE/out wanpinglee/sve:0.1.0`
(then I think I should add "r -g <hg19|hg38|others> -a <breakdancer|breakseq|cnvnator|hydra|delly|lumpy|cnmops> <BAM [BAM ...]>")
and I was able to see the subcommands:

> usage: sve [options]
> 
> Command: align FASTQ->BAM
> realign BAM->BAM
> hg38fix BAM->BAM
> call BAM(s)->VCF
> sve: error: too few arguments

However, I don't know what is the correct syntax to choose Commands.
Moreover, is it possible to run multiple callers with a single command?
Thanks.

**Comment by lslochov** [comment]
Hi, the "sve" binary in the Docker image resides in "/tools/SVE/bin/sve", so the Docker command line would look like:

```
docker run -v <Local input dir>:/tools/SVE/in -v <Local output dir>:/tools/SVE/out wanpinglee/sve:0.1.0 /tools/SVE/bin/sve call -r -g <hg19|hg38|others> -a <breakdancer|breakseq|cnvnator|hydra|delly|lumpy|cnmops> <BAM [BAM ...]>
```

Let me know if you have any further issues.

**Comment by MaestSi** [comment]
Thank you,
I have copied the bam file $BAM and the fasta reference Homo_sapiens_assembly38.fasta in my local input dir $WORKING_DIR, and set $REFERENCE=Homo_sapiens_assembly38.fasta; however, when running:
 `docker run -v $WORKING_DIR:/tools/SVE/in -v $OUTPUT_DIR:/tools/SVE/out wanpinglee/sve:0.1.0 /tools/SVE/bin/sve call -r $REFERENCE -g $GENOME_VER -a cnvnator $BAM`
I have:

> ERROR: Cannot open reference file: Homo_sapiens_assembly38.fasta

Any guesses?

**Comment by lslochov** [comment]
You need to specify the path to the reference genome in the Docker image's folder hierarchy, so instead of `-r $REFERENCE` you need to use `-r /tools/SVE/in/$REFERENCE`

**Comment by MaestSi** [comment]
Thank you, now the previous error is solved.
I thought that the part of code "-v $WORKING_DIR:/tools/SVE/in" was supposed to tell docker where to look for inputs, but I am very new to this. So, thank you again!

**Comment by MaestSi** [comment]
Just to sum up for other people unfamiliar with docker, my command is:
WORKING_DIR=/mnt/cifs01/simone/NA12878
OUTPUT_DIR=$WORKING_DIR/SVE_output_docker
MNT_INPUT_DIR=/tools/SVE/in
MNT_OUTPUT_DIR=/tools/SVE/out
REFERENCE=Homo_sapiens_assembly38.fasta
GENOME_VER=hg38

docker run -v $WORKING_DIR:$MNT_INPUT_DIR -v $OUTPUT_DIR:$MNT_OUTPUT_DIR wanpinglee/sve:0.1.0 /tools/SVE/bin/sve call -r $MNT_INPUT_DIR"/"$REFERENCE -g $GENOME_VER -a cnvnator $MNT_INPUT_DIR"/"$BAM -o $MNT_OUTPUT_DIR
