### ISSUE TITLE
set options for each caller

### ISSUE THREAD

**Issue by C4t3** [TheJacksonLaboratory/SVE#18]
Hi,
how can I set the options for the different callers? For example, what if I want to change the size with -s option for breakdancer? Is it possible?

**Comment by lslochov** [comment]
Hi, SVE has wrapper scripts for each caller that uses default parameters when running a given caller. If you want to change those parameters, you will have to invoke each caller directly. When SVE is compiled, the binary executables for each caller can be found under the "src" folder.
