### ISSUE TITLE
Root requirement is incomplete in README.md

### ISSUE THREAD

**Issue by erland13** [TheJacksonLaboratory/SVE#2]
You should update the requirement for Root to version 5.34.36 or earlier - later versions no longer provide libCint, but have switched to libCling

**Comment by MaestSi** [comment]
I personally had that issue too, but solved it removing -lCint from Makefile in SVE/src/speedseq/src/cnvnator. CNVnator seems to be working properly.

**Comment by erland13** [comment]
It's actually a bit peculiar where '-lCint' comes from - it is not present in CNVnator 0.3.3 distribution (https://github.com/abyzovlab/CNVnator)
