### ISSUE TITLE
Errors in FusorSV

### ISSUE THREAD

**Issue by lh12565** [TheJacksonLaboratory/SVE#20]
Hi!
When I run FusorSV, there is a mistake as follows:
error: option -f not recognized

my command:
```
python FusorSV.py -f data/models/default.pickle -r /data1/ref/hg38/GATK_bundle/Homo_sapiens_assembly38.fasta -i /data1/lh/project/sve/vcfs/ -o test/
```

Thanks!

**Comment by lslochov** [comment]
Hi, can you please tell me which branch of SVE you checked out, as well as the commit hash?
