### ISSUE TITLE
sve python script ignoring loaded environment 

### ISSUE THREAD

**Issue by mforde84** [TheJacksonLaboratory/SVE#3]
Hi,

We're using lmod. There's a default installation of python provided through the system path, but users load production environments of python as well, and SVE is installed specifically to one of these environments:

for eg., 
$ which python
/usr/bin/python
$ python --version #default path
2.7.6
$ module load python/2.7.14 #loads production path
$ which python
/apps/software/compiler/gcc/python/2.7.14/bin/python
$ python --version #version used to compile breakseq
2.7.14

sve is installed to the 2.7.14 python toolchain, and unfortunately when sve wraps commands through the stage package, it fails to load the stipulated lmod modules and automatically runs from the default system path. This is problematic for library linking. E.g., if breakseqs compilation is linked to python/2.7.14, it won't run with libraries linking to python/2.7.6. Objectively, say I wanted to add command to the beginning of all wrapped commands, e.g.,

module load python/2.7.13 && --WRAPPED COMMAND--

Which aspect of your code do I need to modify?

**Comment by mforde84** [comment]
bump

**Comment by MalhotraAnkit** [comment]
Dear Martin, we will investigate this issue and get back to you next week.

**Comment by mforde84** [comment]
Thanks appreciate the help. I've been trying to pick through the code, 
but have been having some difficulty. I think this might be related to 
the python stage import. Ideally I'm just looking for a way to append a 
command to the beginning of each wrapped command generated by SVE, so 
maybe your experience with the code base it might be more 
straightforward for you to figure out where to make the change.

M

**Comment by mforde84** [comment]
Hi, I just wanted to touch base on this. Any chance you've had time to narrow down the issue in the scripting?

Thanks,
Martin

**Comment by lslochov** [comment]
Hi Martin, I think I know how to fix this, at least in Breakseq's case. There's a line in the Breakseq wrapper in SVE that specifies which Python to use. It's supposed to figure this out automatically from the system environment, but perhaps this method doesn't detect python loaded by lmod. Regardless, you can manually configure the python path used by Breakseq by modifying line 48 of "(SVE_root_directory)/stages/breakseq.py" The wrappers for the other stages can be modified in this folder as well.

**Comment by mforde84** [comment]
Thanks, this was helpful. However, I keep running into issues with deprecated code. I know you guys provide a dependency list for python library names, however I would also need versioning as well. E.g., 

(python_env) [root@cri16in001 SVE]# python /apps/software/gcc-4.9.4/SVE/1.0.0/SVE/src/breakseq2/scripts/run_breakseq2.py --bwa /apps/software/gcc-4.9.4/SVE/1.0.0/SVE/src/bwa/bwa --samtools /apps/software/gcc-4.9.4/SVE/1.0.0/SVE/src/samtools/samtools --reference new_genome.fa --work /group/cgl-molpath-lab/spatil/SVE/output/CGL1282S1_AGTTCCG_merged.sorted.RG.abraPass1.sorted.noDups_S35/ --min_span 2 --window 500 --min_overlap 2 --junction_length 1000 --bams CGL1282S1_AGTTCCG_merged.sorted.RG.abraPass1.sorted.noDups.bam --nthreads 4 --bplib_gff /apps/software/gcc-4.9.4/SVE/1.0.0/SVE/data/breakseq_bplib/breakseq2_bplib_20150129.gff
INFO 2018-05-22 15:17:20,107 /apps/software/gcc-4.9.4/SVE/1.0.0/SVE/src/breakseq2/scripts/run_breakseq2.py Command-line: /apps/software/gcc-4.9.4/SVE/1.0.0/SVE/src/breakseq2/scripts/run_breakseq2.py --bwa /apps/software/gcc-4.9.4/SVE/1.0.0/SVE/src/bwa/bwa --samtools /apps/software/gcc-4.9.4/SVE/1.0.0/SVE/src/samtools/samtools --reference new_genome.fa --work /group/cgl-molpath-lab/spatil/SVE/output/CGL1282S1_AGTTCCG_merged.sorted.RG.abraPass1.sorted.noDups_S35/ --min_span 2 --window 500 --min_overlap 2 --junction_length 1000 --bams CGL1282S1_AGTTCCG_merged.sorted.RG.abraPass1.sorted.noDups.bam --nthreads 4 --bplib_gff /apps/software/gcc-4.9.4/SVE/1.0.0/SVE/data/breakseq_bplib/breakseq2_bplib_20150129.gff
INFO 2018-05-22 15:17:20,219 breakseq2_workflow   Generating breakpoint-library using /apps/software/gcc-4.9.4/SVE/1.0.0/SVE/data/breakseq_bplib/breakseq2_bplib_20150129.gff
Traceback (most recent call last):
  File "/apps/software/gcc-4.9.4/SVE/1.0.0/SVE/src/breakseq2/scripts/run_breakseq2.py", line 28, in <module>
    args.keep_temp, args.window, args.junction_length))
  File "/apps/software/gcc-4.9.4/SVE/1.0.0/python_env/lib/python2.7/site-packages/breakseq2/breakseq_top.py", line 96, in breakseq2_workflow
    breakseq_index.generate_bplib(bplib_gff, reference, bplib, junction_length)
  File "/apps/software/gcc-4.9.4/SVE/1.0.0/python_env/lib/python2.7/site-packages/breakseq2/breakseq_index.py", line 47, in generate_bplib
    flanks = sv.get_flanks()
  File "/apps/software/gcc-4.9.4/SVE/1.0.0/python_env/lib/python2.7/site-packages/breakseq2/biopy/io/SV.py", line 120, in get_flanks
    seqA=seqs.get_sequence(*seqs.get_window(self.name, self.start))
  File "/apps/software/gcc-4.9.4/SVE/1.0.0/python_env/lib/python2.7/site-packages/breakseq2/biopy/io/Fasta.py", line 20, in get_sequence
    seq = self.seqs[name].seq
KeyError: '1'

(python_env) [root@cri16in001 SVE]# pip freeze
biopython==1.65
BreakSeq2===-2.2-
bx-python==0.8.1
certifi==2018.4.16
chardet==3.0.4
CrossMap==0.2.7
Cython==0.28.2
HTSeq==0.9.1
idna==2.6
mygene==3.0.0
numpy==1.14.3
pysam==0.7.7
python-lzo==1.12
requests==2.18.4
scipy==1.1.0
six==1.11.0
subprocess32==3.2.7
urllib3==1.22

I believe this is related to versioning of biopython. I've tried rolling back to 1.48, but I've yet to find an appropriate version that works with breakseq2.

**Comment by lslochov** [comment]
Hi Martin, from the looks of your error message, it looks like the code is trying to access an invalid chromosome or contig. Since the missing key is '1', I wonder if you're using chromosome names with the "chr" prefix. The program may be expecting to see "chr1" instead of "1".

**Comment by lslochov** [comment]
Hi Martin, did this resolve your issue? If so, then I'm going to close this thread.

**Comment by mforde84** [comment]
Yes, should be resolved. Thanks for your help.
