### ISSUE TITLE
call error

### ISSUE THREAD

**Issue by hjzhou988** [TheJacksonLaboratory/SVE#4]
Hi developers,

After installing SVE, I tried the call function for every algorithm, and there is always an "call error" message. Though for every algorithm, the message content is different. I don't have experience in software developing, so I wonder whether it is something that's easy to fix. I am using CentOS 6.9. Also, I made sure that every required module of python 2.7 was installed.

For example, breakdancer:

```
    perl /u/flashscratch/flashscratch1/h/hjzhou/SVE/src/breakdancer-1.4.5/perl/bam2cfg.pl -q 30 -n 10000 /u/nobackup/eeskin2/jhsul/bipolar/processed_BAM_hdd/LP6005646-DNA_A01/LP6005646-DNA_A01.dedup.realigned.recal.bam /u/nobackup/eeskin2/jhsul/bipolar/processed_BAM_hdd/LP6005646-DNA_A02/LP6005646-DNA_A02.dedup.realigned.recal.bam > /u/flashscratch/flashscratch1/h/hjzhou/SVE/output/joint_S4/bd_confg.txt
    call error: Can’t locate GD/Graph/bars.pm in @INC (@INC contains: /u/flashscratch/flashscratch1/h/hjzhou/SVE/src/perl-lib/lib/perl5/x86_64-linux-thread-multi /u/flashscratch/flashscratch1/h/hjzhou/SVE/src/perl-lib/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /u/flashscratch/flashscratch1/h/hjzhou/SVE/src/perl-lib/lib/perl5/GD/Graph/histogram.pm line 21.
    BEGIN failed--compilation aborted at /u/flashscratch/flashscratch1/h/hjzhou/SVE/src/perl-lib/lib/perl5/GD/Graph/histogram.pm line 21.
    Compilation failed in require at /u/flashscratch/flashscratch1/h/hjzhou/SVE/src/breakdancer-1.4.5/perl/bam2cfg.pl line 8.
    BEGIN failed--compilation aborted at /u/flashscratch/flashscratch1/h/hjzhou/SVE/src/breakdancer-1.4.5/perl/bam2cfg.pl line 8.
```

For hydra, it got error:
```call error: /u/local/apps/python/2.7.2/bin/python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory```

For lumpy, it got error:
```
call error: Sourcing executables from /u/flashscratch/flashscratch1/h/hjzhou/SVE/src/lumpy-sv/bin/lumpyexpress.config ...
    
    Checking for required python modules (/u/home/h/hjzhou/miniconda2/bin/python)...
    sambamba-view:  (Broken pipe)
    Traceback (most recent call last):
      File “/u/flashscratch/flashscratch1/h/hjzhou/SVE/src/lumpy-sv//scripts/bamkit/bamlibs.py”, line 6, in <module>
        import pysam
      File “/u/home/h/hjzhou/.local/lib/python2.7/site-packages/pysam/__init__.py”, line 5, in <module>
        from pysam.libchtslib import *
    ImportError: /u/home/h/hjzhou/.local/lib/python2.7/site-packages/pysam/libchtslib.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8
```

**Comment by lslochov** [comment]
Hi there, it appears that you're missing some of the dependencies. The easiest way around this is to just use the Docker version, which comes packaged with all the dependencies, otherwise you'll have to manually install each missing dependency.

**Comment by lslochov** [comment]
Hi, did this resolve your issue? If so, then I'm going to close this thread.

**Comment by hjzhou988** [comment]
Thank you for asking. We are still not able to install docker in our system yet... so I don't know. Probably we have to install each algorithm separately.

**Comment by lslochov** [comment]
Ok, let me know if you need help with this, or have any further questions.

**Comment by hjzhou988** [comment]
Alright. Thank you!
