### ISSUE TITLE
Can SVE be used to detect SVs in Plant Genomes?

### ISSUE THREAD

**Issue by songtaogui** [TheJacksonLaboratory/SVE#5]
Dear SVE developers,

I have learned that all your test data are based on human genomes. Since I am dealing with plant genomes, I was wondering that can SVE be used to detect SVs in Plant Genomes?

best wishes!

**Comment by MalhotraAnkit** [comment]
We are working on this issue currently. We want to make SVE/fusorSV work with new references and other species. Will keep you posted, 

Regards,
