### ISSUE TITLE
no file of scripts/FusorSV/data/models/default.pickle 

### ISSUE THREAD

**Issue by arkyl** [TheJacksonLaboratory/SVE#6]
Hi,
We were trying to run the Fusor directly with existing vcfs from our previous pipeline. However, I could not find the file default.pickle. There is no data subdirectory under scripts/FusorSV/. Any thought on this? Thanks very much!

**Comment by lslochov** [comment]
Hi, the "default.pickle" file refers to the default model, which was trained for the FusorSV publication. If you're training your own model, you don't need this, as a new model file will be generated when you run FusorSV (In this case, you would leave out the "-f scripts/FusorSV/data/models/default.pickle" from the command line). However, if you were planning to do SV discovery using the previously trained model, then I can provide the "default.pickle" file to you. My apologies for the confusion—I was under the impression that that file was included in the SVE distribution.

**Comment by lslochov** [comment]
Hi, quick update, you can find the data subdirectory and the "default.pickle" file by unzipping the "data.tar.gz" file in scripts/FusorSV/ first.

**Comment by arkyl** [comment]
Thanks much for the quick reply and solution. I found the desired file.
