### ISSUE TITLE
Joint calling separation

### ISSUE THREAD

**Issue by jiangyuanluo** [TheJacksonLaboratory/SVE#9]
I saw that sve lets hydra do joint calling, but each sample has a vcf file for hydra when fed into FusorSV. How does sve separate the joint calling result? If I'm running hydra on multiple samples by myself and feed into FusorSV is it necessary to do joint calling?

**Comment by lslochov** [comment]
Hi, thanks for your interest in FusorSV. As written, FusorSV only supports single sample VCFs as input. That said, FusorSV is multi-sample in the sense that it will use the best information from every input sample in preparing its output.
